name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: linux-ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: astral-sh/setup-uv@v5.4.1
      - run: uv run pytest
